### ISSUE TITLE
Problems with Navbar

### ISSUE THREAD

**Issue by Ducccc1614** [bucketrobotics/palmerroboticsclub.github.io#69]
Navbar does not go away when clicking links

Make navbar close when clicking links

Device: iPad Pro 2021 11’
OS: iPadOS 16.3
Web Browser: Safari - 16.2 

Steps to reproduce:

open nav bar
click on link

**Comment by arno99xx** [comment]
I tried to reproduce this glitch, nothing is wrong. Are you sure this is not just a problem with your device?

**Comment by Ducccc1614** [comment]
glitch only appears on phone

**Comment by pythonSnake5036** [comment]
only appears on sm breakpoint
